### ISSUE TITLE
Plug in errors

### ISSUE THREAD

**Issue by V1d1o7** [daftspunk/dishsmith-plugin#1]
Step 2 in the instructions, the link gives a 404 error. 
I assumed [this plugin](https://github.com/rainlab/user-plugin) as the same, but i end up with this error:
![Screen Shot 2021-02-09 at 9 50 02 PM](https://user-images.githubusercontent.com/56764154/107466250-d4e78400-6b20-11eb-9878-8d73eff9b352.png)

**Comment by daftspunk** [comment]
Check that you have the `RainLab.User` plugin installed properly. The class this error complains about is provided by the RainLab.User plugin.
